FROM python:3.13

WORKDIR /app

# Requirements installieren
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Quellcode kopieren
COPY main.py .

EXPOSE 5000

CMD ["python", "main.py"]